version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
      - index.html
      - error.html
      - favicon.ico
      - KennethJCartwrightResume.pdf
      - styles/*
      - images/*
      - data/*
      - dist/kjcwebsite_webpack_bundle.js
